name: tests-services

on:
  push:
    branches:
      - chore/testing
  pull_request:
    branches:
      - chore/testing

jobs:
  test-services:
    runs-on: ubuntu-latest
    environment: testing

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install
      - run: cd frontend && npx playwright install --with-deps
      - run: pnpm test:all
